# Generated by Django 5.2.3 on 2025-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
