# Generated by Django 5.2.3 on 2025-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events_image/img1.ivif', null=True, upload_to='events_image'),
        ),
    ]
