# Generated by Django 5.2.3 on 2025-08-01 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Enter your phone number like 01XXXXXXXXX. '+880' will be added automatically.", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+8801XXXXXXXXX'.", regex='^\\+8801\\d{9}$')]),
        ),
    ]
