# Generated by Django 5.2.3 on 2025-08-01 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Enter your phone number like 01XXXXXXXXX. '+880' will be added automatically if not included.", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '01XXXXXXXXX' or '+8801XXXXXXXXX'.", regex='^(\\+8801|01)\\d{9}$')]),
        ),
    ]
